# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/appau',
                'doc_host': 'https://Matt3164.github.io',
                'git_url': 'https://github.com/Matt3164/appau',
                'lib_path': 'appau'},
  'syms': {'appau.core': {'appau.core.foo': ('core.html#foo', 'appau/core.py')}}}
